// BandelBanget AI — Indonesian OpenAI-compatible gateway proxy.
// /v1/models is public; catalog probed 2026-08-14 (36 chat models, graded A/B/C).
export default {
  id: "bandelbanget",
  alias: "bbg",
  uiAlias: "bbg",
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  priority: 80,
  hasFree: false,
  display: {
    name: "BandelBanget AI",
    icon: "bolt",
    color: "#7C3AED",
    textIcon: "BB",
    website: "https://bandelbanget.xyz",
    notice: { apiKeyUrl: "https://bandelbanget.xyz" },
  },
  transport: {
    baseUrl: "https://bandelbanget.xyz/v1/chat/completions",
    validateUrl: "https://bandelbanget.xyz/v1/models",
  },
  passthroughModels: true,
  models: [
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-sonnet-4.5-thinking", name: "Claude Sonnet 4.5 (Thinking)" },
    { id: "claude-sonnet-4.6-b", name: "Claude Sonnet 4.6 (B)" },
    { id: "claude-opus-5-b", name: "Claude Opus 5 (B)" },
    { id: "claude-opus-4.8-b", name: "Claude Opus 4.8 (B)" },
    { id: "claude-sonnet-5-b", name: "Claude Sonnet 5 (B)" },
    { id: "gpt-5.6", name: "GPT 5.6" },
    { id: "gpt-5.5", name: "GPT 5.5" },
    { id: "gpt-5.6-sol", name: "GPT 5.6 Sol" },
    { id: "gpt-5.6-sol-xhigh", name: "GPT 5.6 Sol (xHigh)" },
    { id: "gpt-5.6-luna", name: "GPT 5.6 Luna" },
    { id: "gpt-5.6-terra", name: "GPT 5.6 Terra" },
    { id: "gpt-5.6-sol-b", name: "GPT 5.6 Sol (B)" },
    { id: "gpt-5.6-luna-b", name: "GPT 5.6 Luna (B)" },
    { id: "gpt-5.6-terra-b", name: "GPT 5.6 Terra (B)" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-mod", name: "DeepSeek V4 Mod" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro-b", name: "DeepSeek V4 Pro (B)" },
    { id: "glm-5.3", name: "GLM 5.3" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "kimi-k2.7-code-highspeed", name: "Kimi K2.7 Code (Highspeed)" },
    { id: "qwen3.8-max", name: "Qwen3.8 Max" },
    { id: "qwen3.8-max-b", name: "Qwen3.8 Max (B)" },
    { id: "qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "grok-4.3-b", name: "Grok 4.3 (B)" },
    { id: "mistral-large-3-675b-instruct", name: "Mistral Large 3 675B Instruct" },
    { id: "hy3", name: "HY3" },
    { id: "auto", name: "Auto" },
    { id: "auto-debug", name: "Auto Debug" },
  ],
  serviceKinds: ["llm"],
};
