export default {
  id: "cline",
  priority: 80,
  alias: "cl",
  uiAlias: "cl",
  display: {
    name: "Cline",
    icon: "smart_toy",
    color: "#5B9BD5",
    textIcon: "CL",
    website: "https://cline.bot",
    notice: {
      signupUrl: "https://cline.bot",
    },
  },
  category: "oauth",
  transport: {
    baseUrl: "https://api.cline.bot/api/v1/chat/completions",
    headers: {
      "HTTP-Referer": "https://cline.bot",
      "X-Title": "Cline",
    },
    tokenUrl: "https://api.cline.bot/api/v1/auth/token",
    refreshUrl: "https://api.cline.bot/api/v1/auth/refresh",
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
      hooks: [
        "clineHeaders",
      ],
    },
  },
  models: [
    // ── Regenerated 2026-09-11 from the live Cline/OpenRouter catalog (435 raw lanes) ──
    // Curated: :batch twins, openrouter/* meta-lanes, ~ rolling aliases, perceptron safety classifier,
    // and image/audio/music-only lanes struck (no chat transport); :free lanes KEPT (pricing inherits siblings).
    { id: "inception/mercury-2.5", name: "Mercury 2.5" },
    { id: "nex-agi/nex-n2.5-mini:free", name: "Nex N2.5 Mini (Free)" },
    { id: "nex-agi/nex-n2.5-pro:free", name: "Nex N2.5 Pro (Free)" },
    { id: "openai/gpt-6-astra", name: "GPT 6 Astra" },
    { id: "openai/gpt-6-astra-pro", name: "GPT 6 Astra Pro" },
    { id: "inclusionai/ling-3.0-flash-sante:free", name: "Ling 3.0 Flash Sante (Free)" },
    { id: "qwen/qwen3.8-max-0902", name: "Qwen3.8 Max 0902" },
    { id: "meta/muse-spark-1.3-contributor", name: "Muse Spark 1.3 Contributor" },
    { id: "meta/muse-spark-1.3", name: "Muse Spark 1.3" },
    { id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash" },
    { id: "anthropic/claude-fable-5.1", name: "Claude Fable 5.1" },
    { id: "ibm-granite/granite-4.2-8b", name: "Granite 4.2 8b" },
    { id: "tencent/hy4-preview", name: "Hy4 Preview" },
    { id: "inclusionai/ling-3.0-flash-fin", name: "Ling 3.0 Flash Fin" },
    { id: "inclusionai/ling-3.0-flash-fin:free", name: "Ling 3.0 Flash Fin (Free)" },
    { id: "qwen/qwen3.8-flash", name: "Qwen3.8 Flash" },
    { id: "z-ai/glm-5.3-flash", name: "GLM 5.3 Flash" },
    { id: "meta/muse-spark-1.2-contributor", name: "Muse Spark 1.2 Contributor" },
    { id: "deepseek/deepseek-v4-flash-vision-exp", name: "Deepseek V4 Flash Vision Exp" },
    { id: "tencent/hy-mt2-1.8b", name: "Hy Mt2 1.8b" },
    { id: "tencent/hy-mt2-30b-a3b", name: "Hy Mt2 30b A3B" },
    { id: "tencent/hy-mt2-7b", name: "Hy Mt2 7b" },
    { id: "z-ai/glm-5.3", name: "GLM 5.3" },
    { id: "qwen/qwen3.8-27b", name: "Qwen3.8 27b" },
    { id: "dots-studio/dots-3-note-preview:free", name: "Dots 3 Note Preview (Free)" },
    { id: "google/gemini-3.7-flash", name: "Gemini 3.7 Flash" },
    { id: "bytedance-seed/seed-2-1-turbo", name: "Seed 2 1 Turbo" },
    { id: "qwen/qwen3.8-2.4t-a95b", name: "Qwen3.8 2.4t A95B" },
    { id: "bytedance-seed/seed-2.0-code", name: "Seed 2.0 Code" },
    { id: "deepseek/deepseek-v4-pro-0813", name: "Deepseek V4 Pro 0813" },
    { id: "x-ai/grok-4.6", name: "Grok 4.6" },
    { id: "liquid/lfm-2.5-2.6b:free", name: "Lfm 2.5 2.6b (Free)" },
    { id: "nvidia/nemotron-3.5-lightning", name: "Nemotron 3.5 Lightning" },
    { id: "nvidia/nemotron-3.5-lightning:free", name: "Nemotron 3.5 Lightning (Free)" },
    { id: "sakana/sakana-namazu", name: "Sakana Namazu" },
    { id: "upstage/solar-pro4", name: "Solar Pro4" },
    { id: "meta/muse-glimmer-30b", name: "Muse Glimmer 30b" },
    { id: "meta/muse-spark-1.2", name: "Muse Spark 1.2" },
    { id: "deepseek/deepseek-v4-flash-0731", name: "Deepseek V4 Flash 0731" },
    { id: "thinkingmachines/inkling-small", name: "Inkling Small" },
    { id: "thinkingmachines/inkling-small:free", name: "Inkling Small (Free)" },
    { id: "qwen/qwen3.7-flash", name: "Qwen3.7 Flash" },
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5" },
    { id: "inclusionai/ling-3.0-flash", name: "Ling 3.0 Flash" },
    { id: "poolside/laguna-s-2.1", name: "Laguna S 2.1" },
    { id: "poolside/laguna-s-2.1:free", name: "Laguna S 2.1 (Free)" },
    { id: "google/gemini-3.6-flash", name: "Gemini 3.6 Flash" },
    { id: "google/gemini-3.5-flash-lite", name: "Gemini 3.5 Flash Lite" },
    { id: "meituan/longcat-2.0", name: "Longcat 2.0" },
    { id: "thinkingmachines/inkling", name: "Inkling" },
    { id: "thinkingmachines/inkling:free", name: "Inkling (Free)" },
    { id: "moonshotai/kimi-k3", name: "Kimi K3" },
    { id: "meta/muse-spark-1.1", name: "Muse Spark 1.1" },
    { id: "kwaipilot/kat-coder-pro-v2.5", name: "Kat Coder Pro V2.5" },
    { id: "openai/gpt-5.6-luna-pro", name: "GPT 5.6 Luna Pro" },
    { id: "openai/gpt-5.6-luna", name: "GPT 5.6 Luna" },
    { id: "openai/gpt-5.6-terra-pro", name: "GPT 5.6 Terra Pro" },
    { id: "openai/gpt-5.6-terra", name: "GPT 5.6 Terra" },
    { id: "openai/gpt-5.6-sol-pro", name: "GPT 5.6 Sol Pro" },
    { id: "openai/gpt-5.6-sol", name: "GPT 5.6 Sol" },
    { id: "x-ai/grok-4.5", name: "Grok 4.5" },
    { id: "aion-labs/aion-3.0-mini", name: "Aion 3.0 Mini" },
    { id: "aion-labs/aion-3.0", name: "Aion 3.0" },
    { id: "tencent/hy3", name: "Hy3" },
    { id: "poolside/laguna-xs-2.1", name: "Laguna Xs 2.1" },
    { id: "poolside/laguna-xs-2.1:free", name: "Laguna Xs 2.1 (Free)" },
    { id: "anthropic/claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "google/gemini-3.1-flash-lite-image", name: "Gemini 3.1 Flash Lite Image" },
    { id: "sakana/fugu-ultra", name: "Fugu Ultra" },
    { id: "google/gemini-3.1-flash-image", name: "Gemini 3.1 Flash Image" },
    { id: "cohere/north-mini-code:free", name: "North Mini Code (Free)" },
    { id: "z-ai/glm-5.2", name: "GLM 5.2" },
    { id: "moonshotai/kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "anthropic/claude-fable-5", name: "Claude Fable 5" },
    { id: "nvidia/nemotron-3.5-content-safety", name: "Nemotron 3.5 Content Safety" },
    { id: "nvidia/nemotron-3.5-content-safety:free", name: "Nemotron 3.5 Content Safety (Free)" },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra 550b A55B" },
    { id: "nvidia/nemotron-3-ultra-550b-a55b:free", name: "Nemotron 3 Ultra 550b A55B (Free)" },
    { id: "qwen/qwen3.7-plus", name: "Qwen3.7 Plus" },
    { id: "minimax/minimax-m3", name: "Minimax M3" },
    { id: "stepfun/step-3.7-flash", name: "Step 3.7 Flash" },
    { id: "anthropic/claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "qwen/qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "x-ai/grok-build-0.1", name: "Grok Build 0.1" },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "google/gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite" },
    { id: "openai/gpt-chat-latest", name: "GPT Chat Latest" },
    { id: "x-ai/grok-4.3", name: "Grok 4.3" },
    { id: "mistralai/mistral-medium-3-5", name: "Mistral Medium 3 5" },
    { id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", name: "Nemotron 3 Nano Omni 30b A3B Reasoning (Free)" },
    { id: "qwen/qwen3.5-plus-20260420", name: "Qwen3.5 Plus 20260420" },
    { id: "qwen/qwen3.6-flash", name: "Qwen3.6 Flash" },
    { id: "qwen/qwen3.6-35b-a3b", name: "Qwen3.6 35b A3B" },
    { id: "qwen/qwen3.6-max-preview", name: "Qwen3.6 Max Preview" },
    { id: "qwen/qwen3.6-27b", name: "Qwen3.6 27b" },
    { id: "openai/gpt-5.5-pro", name: "GPT 5.5 Pro" },
    { id: "openai/gpt-5.5", name: "GPT 5.5" },
    { id: "deepseek/deepseek-v4-pro", name: "Deepseek V4 Pro" },
    { id: "deepseek/deepseek-v4-flash", name: "Deepseek V4 Flash" },
    { id: "tencent/hy3-preview", name: "Hy3 Preview" },
    { id: "xiaomi/mimo-v2.5-pro", name: "Mimo V2.5 Pro" },
    { id: "xiaomi/mimo-v2.5", name: "Mimo V2.5" },
    { id: "moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "anthropic/claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "z-ai/glm-5.1", name: "GLM 5.1" },
    { id: "google/gemma-4-26b-a4b-it", name: "Gemma 4 26b A4B IT" },
    { id: "google/gemma-4-26b-a4b-it:free", name: "Gemma 4 26b A4B IT (Free)" },
    { id: "google/gemma-4-31b-it", name: "Gemma 4 31b IT" },
    { id: "google/gemma-4-31b-it:free", name: "Gemma 4 31b IT (Free)" },
    { id: "qwen/qwen3.6-plus", name: "Qwen3.6 Plus" },
    { id: "z-ai/glm-5v-turbo", name: "GLM 5v Turbo" },
    { id: "arcee-ai/trinity-large-thinking", name: "Trinity Large Thinking" },
    { id: "x-ai/grok-4.20-multi-agent", name: "Grok 4.20 Multi Agent" },
    { id: "x-ai/grok-4.20", name: "Grok 4.20" },
    { id: "kwaipilot/kat-coder-pro-v2", name: "Kat Coder Pro V2" },
    { id: "rekaai/reka-edge", name: "Reka Edge" },
    { id: "minimax/minimax-m2.7", name: "Minimax M2.7" },
    { id: "openai/gpt-5.4-nano", name: "GPT 5.4 Nano" },
    { id: "openai/gpt-5.4-mini", name: "GPT 5.4 Mini" },
    { id: "mistralai/mistral-small-2603", name: "Mistral Small 2603" },
    { id: "z-ai/glm-5-turbo", name: "GLM 5 Turbo" },
    { id: "nvidia/nemotron-3-super-120b-a12b", name: "Nemotron 3 Super 120b A12B" },
    { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "Nemotron 3 Super 120b A12B (Free)" },
    { id: "bytedance-seed/seed-2.0-lite", name: "Seed 2.0 Lite" },
    { id: "qwen/qwen3.5-9b", name: "Qwen3.5 9b" },
    { id: "openai/gpt-5.4-pro", name: "GPT 5.4 Pro" },
    { id: "openai/gpt-5.4", name: "GPT 5.4" },
    { id: "inception/mercury-2", name: "Mercury 2" },
    { id: "google/gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview" },
    { id: "bytedance-seed/seed-2.0-mini", name: "Seed 2.0 Mini" },
    { id: "google/gemini-3.1-flash-image-preview", name: "Gemini 3.1 Flash Image Preview" },
    { id: "qwen/qwen3.5-35b-a3b", name: "Qwen3.5 35b A3B" },
    { id: "qwen/qwen3.5-27b", name: "Qwen3.5 27b" },
    { id: "qwen/qwen3.5-122b-a10b", name: "Qwen3.5 122b A10B" },
    { id: "qwen/qwen3.5-flash-02-23", name: "Qwen3.5 Flash 02 23" },
    { id: "google/gemini-3.1-pro-preview-customtools", name: "Gemini 3.1 Pro Preview Customtools" },
    { id: "openai/gpt-5.3-codex", name: "GPT 5.3 Codex" },
    { id: "aion-labs/aion-2.0", name: "Aion 2.0" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "qwen/qwen3.5-plus-02-15", name: "Qwen3.5 Plus 02 15" },
    { id: "qwen/qwen3.5-397b-a17b", name: "Qwen3.5 397b A17B" },
    { id: "minimax/minimax-m2.5", name: "Minimax M2.5" },
    { id: "z-ai/glm-5", name: "GLM 5" },
    { id: "qwen/qwen3-max-thinking", name: "Qwen3 Max Thinking" },
    { id: "anthropic/claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "qwen/qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "stepfun/step-3.5-flash", name: "Step 3.5 Flash" },
    { id: "moonshotai/kimi-k2.5", name: "Kimi K2.5" },
    { id: "upstage/solar-pro-3", name: "Solar Pro 3" },
    { id: "minimax/minimax-m2-her", name: "Minimax M2 Her" },
    { id: "writer/palmyra-x5", name: "Palmyra X5" },
    { id: "z-ai/glm-4.7-flash", name: "GLM 4.7 Flash" },
    { id: "openai/gpt-5.2-codex", name: "GPT 5.2 Codex" },
    { id: "bytedance-seed/seed-1.6-flash", name: "Seed 1.6 Flash" },
    { id: "bytedance-seed/seed-1.6", name: "Seed 1.6" },
    { id: "minimax/minimax-m2.1", name: "Minimax M2.1" },
    { id: "z-ai/glm-4.7", name: "GLM 4.7" },
    { id: "google/gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "nvidia/nemotron-3-nano-30b-a3b", name: "Nemotron 3 Nano 30b A3B" },
    { id: "openai/gpt-5.2-chat", name: "GPT 5.2 Chat" },
    { id: "openai/gpt-5.2-pro", name: "GPT 5.2 Pro" },
    { id: "openai/gpt-5.2", name: "GPT 5.2" },
    { id: "mistralai/devstral-2512", name: "Devstral 2512" },
    { id: "relace/relace-search", name: "Relace Search" },
    { id: "z-ai/glm-4.6v", name: "GLM 4.6v" },
    { id: "openai/gpt-5.1-codex-max", name: "GPT 5.1 Codex Max" },
    { id: "amazon/nova-2-lite-v1", name: "Nova 2 Lite V1" },
    { id: "mistralai/ministral-14b-2512", name: "Ministral 14b 2512" },
    { id: "mistralai/ministral-8b-2512", name: "Ministral 8b 2512" },
    { id: "mistralai/ministral-3b-2512", name: "Ministral 3b 2512" },
    { id: "mistralai/mistral-large-2512", name: "Mistral Large 2512" },
    { id: "deepseek/deepseek-v3.2", name: "Deepseek V3.2" },
    { id: "anthropic/claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "openai/gpt-5.1", name: "GPT 5.1" },
    { id: "openai/gpt-5.1-codex", name: "GPT 5.1 Codex" },
    { id: "openai/gpt-5.1-codex-mini", name: "GPT 5.1 Codex Mini" },
    { id: "moonshotai/kimi-k2-thinking", name: "Kimi K2 Thinking" },
    { id: "amazon/nova-premier-v1", name: "Nova Premier V1" },
    { id: "perplexity/sonar-pro-search", name: "Sonar Pro Search" },
    { id: "mistralai/voxtral-small-24b-2507", name: "Voxtral Small 24b 2507" },
    { id: "openai/gpt-oss-safeguard-20b", name: "GPT Oss Safeguard 20b" },
    { id: "minimax/minimax-m2", name: "Minimax M2" },
    { id: "qwen/qwen3-vl-32b-instruct", name: "Qwen3 VL 32b Instruct" },
    { id: "ibm-granite/granite-4.0-h-micro", name: "Granite 4.0 H Micro" },
    { id: "anthropic/claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "qwen/qwen3-vl-8b-thinking", name: "Qwen3 VL 8b Thinking" },
    { id: "qwen/qwen3-vl-8b-instruct", name: "Qwen3 VL 8b Instruct" },
    { id: "qwen/qwen3-vl-30b-a3b-thinking", name: "Qwen3 VL 30b A3B Thinking" },
    { id: "qwen/qwen3-vl-30b-a3b-instruct", name: "Qwen3 VL 30b A3B Instruct" },
    { id: "openai/gpt-5-pro", name: "GPT 5 Pro" },
    { id: "z-ai/glm-4.6", name: "GLM 4.6" },
    { id: "anthropic/claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "deepseek/deepseek-v3.2-exp", name: "Deepseek V3.2 Exp" },
    { id: "thedrummer/cydonia-24b-v4.1", name: "Cydonia 24b V4.1" },
    { id: "relace/relace-apply-3", name: "Relace Apply 3" },
    { id: "qwen/qwen3-vl-235b-a22b-thinking", name: "Qwen3 VL 235b A22B Thinking" },
    { id: "qwen/qwen3-vl-235b-a22b-instruct", name: "Qwen3 VL 235b A22B Instruct" },
    { id: "qwen/qwen3-max", name: "Qwen3 Max" },
    { id: "qwen/qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "deepseek/deepseek-v3.1-terminus", name: "Deepseek V3.1 Terminus" },
    { id: "qwen/qwen3-coder-flash", name: "Qwen3 Coder Flash" },
    { id: "qwen/qwen3-next-80b-a3b-thinking", name: "Qwen3 Next 80b A3B Thinking" },
    { id: "qwen/qwen3-next-80b-a3b-instruct", name: "Qwen3 Next 80b A3B Instruct" },
    { id: "qwen/qwen-plus-2025-07-28", name: "Qwen Plus 2025 07 28" },
    { id: "moonshotai/kimi-k2-0905", name: "Kimi K2 0905" },
    { id: "qwen/qwen3-30b-a3b-thinking-2507", name: "Qwen3 30b A3B Thinking 2507" },
    { id: "nousresearch/hermes-4-405b", name: "Hermes 4 405b" },
    { id: "deepseek/deepseek-chat-v3.1", name: "Deepseek Chat V3.1" },
    { id: "mistralai/mistral-medium-3.1", name: "Mistral Medium 3.1" },
    { id: "z-ai/glm-4.5v", name: "GLM 4.5v" },
    { id: "openai/gpt-5", name: "GPT 5" },
    { id: "openai/gpt-5-mini", name: "GPT 5 Mini" },
    { id: "openai/gpt-5-nano", name: "GPT 5 Nano" },
    { id: "openai/gpt-oss-120b", name: "GPT Oss 120b" },
    { id: "openai/gpt-oss-20b", name: "GPT Oss 20b" },
    { id: "anthropic/claude-opus-4.1", name: "Claude Opus 4.1" },
    { id: "mistralai/codestral-2508", name: "Codestral 2508" },
    { id: "qwen/qwen3-coder-30b-a3b-instruct", name: "Qwen3 Coder 30b A3B Instruct" },
    { id: "qwen/qwen3-30b-a3b-instruct-2507", name: "Qwen3 30b A3B Instruct 2507" },
    { id: "z-ai/glm-4.5", name: "GLM 4.5" },
    { id: "z-ai/glm-4.5-air", name: "GLM 4.5 Air" },
    { id: "qwen/qwen3-235b-a22b-thinking-2507", name: "Qwen3 235b A22B Thinking 2507" },
    { id: "qwen/qwen3-coder", name: "Qwen3 Coder" },
    { id: "bytedance/ui-tars-1.5-7b", name: "UI Tars 1.5 7b" },
    { id: "google/gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite" },
    { id: "qwen/qwen3-235b-a22b-2507", name: "Qwen3 235b A22B 2507" },
    { id: "moonshotai/kimi-k2", name: "Kimi K2" },
    { id: "cognitivecomputations/dolphin-mistral-24b-venice-edition", name: "Dolphin Mistral 24b Venice Edition" },
    { id: "tencent/hunyuan-a13b-instruct", name: "Hunyuan A13b Instruct" },
    { id: "morph/morph-v3-large", name: "Morph V3 Large" },
    { id: "morph/morph-v3-fast", name: "Morph V3 Fast" },
    { id: "baidu/ernie-4.5-vl-424b-a47b", name: "Ernie 4.5 VL 424b A47b" },
    { id: "mistralai/mistral-small-3.2-24b-instruct", name: "Mistral Small 3.2 24b Instruct" },
    { id: "minimax/minimax-m1", name: "Minimax M1" },
    { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "openai/o3-pro", name: "O3 Pro" },
    { id: "google/gemini-2.5-pro-preview", name: "Gemini 2.5 Pro Preview" },
    { id: "deepseek/deepseek-r1-0528", name: "Deepseek R1 0528" },
    { id: "anthropic/claude-opus-4", name: "Claude Opus 4" },
    { id: "anthropic/claude-sonnet-4", name: "Claude Sonnet 4" },
    { id: "mistralai/mistral-medium-3", name: "Mistral Medium 3" },
    { id: "google/gemini-2.5-pro-preview-05-06", name: "Gemini 2.5 Pro Preview 05 06" },
    { id: "meta-llama/llama-guard-4-12b", name: "Llama Guard 4 12b" },
    { id: "qwen/qwen3-30b-a3b", name: "Qwen3 30b A3B" },
    { id: "qwen/qwen3-8b", name: "Qwen3 8b" },
    { id: "qwen/qwen3-14b", name: "Qwen3 14b" },
    { id: "qwen/qwen3-32b", name: "Qwen3 32b" },
    { id: "qwen/qwen3-235b-a22b", name: "Qwen3 235b A22B" },
    { id: "openai/o4-mini-high", name: "O4 Mini High" },
    { id: "openai/o3", name: "O3" },
    { id: "openai/o4-mini", name: "O4 Mini" },
    { id: "openai/gpt-4.1", name: "GPT 4.1" },
    { id: "openai/gpt-4.1-mini", name: "GPT 4.1 Mini" },
    { id: "openai/gpt-4.1-nano", name: "GPT 4.1 Nano" },
    { id: "meta-llama/llama-4-maverick", name: "Llama 4 Maverick" },
    { id: "meta-llama/llama-4-scout", name: "Llama 4 Scout" },
    { id: "deepseek/deepseek-chat-v3-0324", name: "Deepseek Chat V3 0324" },
    { id: "openai/o1-pro", name: "O1 Pro" },
    { id: "mistralai/mistral-small-3.1-24b-instruct", name: "Mistral Small 3.1 24b Instruct" },
    { id: "google/gemma-3-4b-it", name: "Gemma 3 4b IT" },
    { id: "google/gemma-3-12b-it", name: "Gemma 3 12b IT" },
    { id: "cohere/command-a", name: "Command A" },
    { id: "rekaai/reka-flash-3", name: "Reka Flash 3" },
    { id: "google/gemma-3-27b-it", name: "Gemma 3 27b IT" },
    { id: "thedrummer/skyfall-36b-v2", name: "Skyfall 36b V2" },
    { id: "perplexity/sonar-reasoning-pro", name: "Sonar Reasoning Pro" },
    { id: "perplexity/sonar-pro", name: "Sonar Pro" },
    { id: "perplexity/sonar-deep-research", name: "Sonar Deep Research" },
    { id: "mistralai/mistral-saba", name: "Mistral Saba" },
    { id: "openai/o3-mini-high", name: "O3 Mini High" },
    { id: "aion-labs/aion-rp-llama-3.1-8b", name: "Aion Rp Llama 3.1 8b" },
    { id: "qwen/qwen2.5-vl-72b-instruct", name: "Qwen2.5 VL 72b Instruct" },
    { id: "qwen/qwen-plus", name: "Qwen Plus" },
    { id: "openai/o3-mini", name: "O3 Mini" },
    { id: "mistralai/mistral-small-24b-instruct-2501", name: "Mistral Small 24b Instruct 2501" },
    { id: "perplexity/sonar", name: "Sonar" },
    { id: "deepseek/deepseek-r1-distill-llama-70b", name: "Deepseek R1 Distill Llama 70b" },
    { id: "deepseek/deepseek-r1", name: "Deepseek R1" },
    { id: "minimax/minimax-01", name: "Minimax 01" },
    { id: "microsoft/phi-4", name: "Phi 4" },
    { id: "deepseek/deepseek-chat", name: "Deepseek Chat" },
    { id: "sao10k/l3.3-euryale-70b", name: "L3.3 Euryale 70b" },
    { id: "openai/o1", name: "O1" },
    { id: "cohere/command-r7b-12-2024", name: "Command R7b 12 2024" },
    { id: "meta-llama/llama-3.3-70b-instruct", name: "Llama 3.3 70b Instruct" },
    { id: "amazon/nova-lite-v1", name: "Nova Lite V1" },
    { id: "amazon/nova-micro-v1", name: "Nova Micro V1" },
    { id: "amazon/nova-pro-v1", name: "Nova Pro V1" },
    { id: "openai/gpt-4o-2024-11-20", name: "GPT 4o 2024 11 20" },
    { id: "mistralai/mistral-large-2407", name: "Mistral Large 2407" },
    { id: "qwen/qwen-2.5-coder-32b-instruct", name: "Qwen 2.5 Coder 32b Instruct" },
    { id: "thedrummer/unslopnemo-12b", name: "Unslopnemo 12b" },
    { id: "anthracite-org/magnum-v4-72b", name: "Magnum V4 72b" },
    { id: "qwen/qwen-2.5-7b-instruct", name: "Qwen 2.5 7b Instruct" },
    { id: "meta-llama/llama-3.2-1b-instruct", name: "Llama 3.2 1b Instruct" },
    { id: "meta-llama/llama-3.2-3b-instruct", name: "Llama 3.2 3b Instruct" },
    { id: "qwen/qwen-2.5-72b-instruct", name: "Qwen 2.5 72b Instruct" },
    { id: "cohere/command-r-08-2024", name: "Command R 08 2024" },
    { id: "cohere/command-r-plus-08-2024", name: "Command R Plus 08 2024" },
    { id: "sao10k/l3.1-euryale-70b", name: "L3.1 Euryale 70b" },
    { id: "nousresearch/hermes-3-llama-3.1-70b", name: "Hermes 3 Llama 3.1 70b" },
    { id: "nousresearch/hermes-3-llama-3.1-405b", name: "Hermes 3 Llama 3.1 405b" },
    { id: "sao10k/l3-lunaris-8b", name: "L3 Lunaris 8b" },
    { id: "openai/gpt-4o-2024-08-06", name: "GPT 4o 2024 08 06" },
    { id: "meta-llama/llama-3.1-70b-instruct", name: "Llama 3.1 70b Instruct" },
    { id: "meta-llama/llama-3.1-8b-instruct", name: "Llama 3.1 8b Instruct" },
    { id: "mistralai/mistral-nemo", name: "Mistral Nemo" },
    { id: "openai/gpt-4o-mini", name: "GPT 4o Mini" },
    { id: "openai/gpt-4o-mini-2024-07-18", name: "GPT 4o Mini 2024 07 18" },
    { id: "google/gemma-2-27b-it", name: "Gemma 2 27b IT" },
    { id: "openai/gpt-4o", name: "GPT 4o" },
    { id: "openai/gpt-4o-2024-05-13", name: "GPT 4o 2024 05 13" },
    { id: "mistralai/mixtral-8x22b-instruct", name: "Mixtral 8x22B Instruct" },
    { id: "microsoft/wizardlm-2-8x22b", name: "Wizardlm 2 8x22B" },
    { id: "openai/gpt-4-turbo", name: "GPT 4 Turbo" },
    { id: "anthropic/claude-3-haiku", name: "Claude 3 Haiku" },
    { id: "mistralai/mistral-large", name: "Mistral Large" },
    { id: "openai/gpt-3.5-turbo-0613", name: "GPT 3.5 Turbo 0613" },
    { id: "openai/gpt-4-turbo-preview", name: "GPT 4 Turbo Preview" },
    { id: "openrouter/auto", name: "Auto" },
    { id: "openai/gpt-3.5-turbo-instruct", name: "GPT 3.5 Turbo Instruct" },
    { id: "openai/gpt-3.5-turbo-16k", name: "GPT 3.5 Turbo 16k" },
    { id: "mancer/weaver", name: "Weaver" },
    { id: "undi95/remm-slerp-l2-13b", name: "Remm Slerp L2 13b" },
    { id: "gryphe/mythomax-l2-13b", name: "Mythomax L2 13b" },
    { id: "openai/gpt-3.5-turbo", name: "GPT 3.5 Turbo" },
    { id: "openai/gpt-4", name: "GPT 4" },
  ],
  oauth: {
    appBaseUrl: "https://app.cline.bot",
    apiBaseUrl: "https://api.cline.bot",
    authorizeUrl: "https://api.cline.bot/api/v1/auth/authorize",
    tokenExchangeUrl: "https://api.cline.bot/api/v1/auth/token",
    refreshUrl: "https://api.cline.bot/api/v1/auth/refresh",
  },
};
