// CodeCrafters — Indonesian OpenAI-compatible gateway.
// /v1/models is public; catalog probed 2026-08-14 (16 models, IDR pricing).
export default {
  id: "codecrafters",
  alias: "ccr",
  uiAlias: "ccr",
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  priority: 82,
  hasFree: true,
  display: {
    name: "CodeCrafters",
    icon: "code",
    color: "#0878F8",
    textIcon: "CC",
    website: "https://codecrafters.id",
    notice: { apiKeyUrl: "https://codecrafters.id" },
  },
  transport: {
    baseUrl: "https://api.codecrafters.id/v1/chat/completions",
    validateUrl: "https://api.codecrafters.id/v1/models",
  },
  passthroughModels: true,
  models: [
    { id: "gpt-5.5", name: "ChatGPT 5.5" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "codecrafters-v1", name: "CodeCrafters V1" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-flash:free", name: "DeepSeek V4 Flash (Free)" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2.5-free", name: "MiMo V2.5 Free" },
    { id: "MiniMax-M3", name: "MiniMax M3" },
    { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "qwen3.6-Plus", name: "Qwen 3.6 Plus" },
    { id: "qwen3.7-max", name: "Qwen 3.7 Max" },
  ],
  serviceKinds: ["llm"],
};
