// GENERATED by scripts/generate-registry-index.mjs — do not hand-edit.
// Census: 163 imported providers (+ 3 hidden: devin-cli, trae, windsurf).
// Stream handler with disconnect detection - shared for all providers
import p0 from "./a6api.js";
import p1 from "./agentrouter.js";
import p2 from "./agentrouter-pro.js";
import p3 from "./ai21.js";
import p4 from "./alibaba.js";
import p5 from "./alibaba-intl.js";
import p6 from "./alicode.js";
import p7 from "./alicode-intl.js";
import p8 from "./alims-intl.js";
import p9 from "./alitp-intl.js";
import p10 from "./anthropic.js";
import p11 from "./antigravity.js";
import p12 from "./api-airforce.js";
import p13 from "./assemblyai.js";
import p14 from "./aws-polly.js";
import p15 from "./azure.js";
import p16 from "./baidu.js";
import p17 from "./bandelbanget.js";
import p18 from "./baseten.js";
import p19 from "./bazaarlink.js";
import p20 from "./black-forest-labs.js";
import p21 from "./blackbox.js";
import p22 from "./bluesminds.js";
import p23 from "./brave-search.js";
import p24 from "./byteplus.js";
import p25 from "./bytez.js";
import p26 from "./cartesia.js";
import p27 from "./cerebras.js";
import p28 from "./chutes.js";
import p29 from "./claude.js";
import p30 from "./cline.js";
import p31 from "./clinepass.js";
import p32 from "./cloudflare-ai.js";
import p33 from "./codebuddy-cn.js";
import p34 from "./codebuddy-intl.js";
import p35 from "./codecrafters.js";
import p36 from "./codestral.js";
import p37 from "./codex.js";
import p38 from "./cohere.js";
import p39 from "./comfyui.js";
import p40 from "./commandcode.js";
import p41 from "./coqui.js";
import p42 from "./cursor.js";
import p43 from "./databricks.js";
import p44 from "./deepgram.js";
import p45 from "./deepinfra.js";
import p46 from "./deepseek.js";
import p47 from "./devin-cli-pro.js";
import p48 from "./edge-tts.js";
import p49 from "./elevenlabs.js";
import p50 from "./exa.js";
import p51 from "./fal-ai.js";
import p52 from "./featherless.js";
import p53 from "./firecrawl.js";
import p54 from "./fireworks.js";
import p55 from "./fish-audio.js";
import p56 from "./freebuff.js";
import p57 from "./friendliai.js";
import p58 from "./galadriel.js";
import p59 from "./gemini.js";
import p60 from "./gemini-cli.js";
import p61 from "./gigachat.js";
import p62 from "./github.js";
import p63 from "./gitlab.js";
import p64 from "./glm.js";
import p65 from "./glm-cn.js";
import p66 from "./google-pse.js";
import p67 from "./google-tts.js";
import p68 from "./grok-cli.js";
import p69 from "./grok-web.js";
import p70 from "./groq.js";
import p71 from "./heroku.js";
import p72 from "./huggingface.js";
import p73 from "./hyperbolic.js";
import p74 from "./iflow.js";
import p75 from "./inworld.js";
import p76 from "./jembatanai.js";
import p77 from "./jerouter.js";
import p78 from "./jina-ai.js";
import p79 from "./jina-reader.js";
import p80 from "./kilo-gateway.js";
import p81 from "./kilocode.js";
import p82 from "./kimchi.js";
import p83 from "./kimi.js";
import p84 from "./kiro.js";
import p85 from "./linkup.js";
import p86 from "./llamagate.js";
import p87 from "./llm7.js";
import p88 from "./local-device.js";
import p89 from "./madefaka.js";
import p90 from "./mimo-free.js";
import p91 from "./minimax.js";
import p92 from "./minimax-cn.js";
import p93 from "./mistral.js";
import p94 from "./mmf.js";
import p95 from "./morph.js";
import p96 from "./muse-spark-lite.js";
import p97 from "./muse-spark-web.js";
import p98 from "./mytraceroute.js";
import p99 from "./nanobanana.js";
import p100 from "./nanogpt.js";
import p101 from "./nebius.js";
import p102 from "./nesarouter.js";
import p103 from "./nscale.js";
import p104 from "./nvidia.js";
import p105 from "./ollama.js";
import p106 from "./ollama-local.js";
import p107 from "./ollama-search.js";
import p108 from "./openai.js";
import p109 from "./opencode.js";
import p110 from "./opencode-go.js";
import p111 from "./openrouter.js";
import p112 from "./ovhcloud.js";
import p113 from "./perplexity.js";
import p114 from "./perplexity-agent.js";
import p115 from "./perplexity-web.js";
import p116 from "./playht.js";
import p117 from "./poolside.js";
import p118 from "./predibase.js";
import p119 from "./publicai.js";
import p120 from "./qoder.js";
import p121 from "./qwen.js";
import p122 from "./qwen-v2.js";
import p123 from "./qzz.js";
import p124 from "./recraft.js";
import p125 from "./runwayml.js";
import p126 from "./sambanova.js";
import p127 from "./sdwebui.js";
import p128 from "./searchapi.js";
import p129 from "./searxng.js";
import p130 from "./selfhosted-embedding.js";
import p131 from "./selfhosted-stt.js";
import p132 from "./selfhosted-tts.js";
import p133 from "./serper.js";
import p134 from "./siliconflow.js";
import p135 from "./snowflake.js";
import p136 from "./stability-ai.js";
import p137 from "./tavily.js";
import p138 from "./tencent.js";
import p139 from "./together.js";
import p140 from "./tokenharbor.js";
import p141 from "./tokenrouter.js";
import p142 from "./topaz.js";
import p143 from "./tortoise.js";
import p144 from "./upstage.js";
import p145 from "./venice.js";
import p146 from "./vercel-ai-gateway.js";
import p147 from "./vertex.js";
import p148 from "./vertex-partner.js";
import p149 from "./volcengine.js";
import p150 from "./volcengine-ark.js";
import p151 from "./voyage-ai.js";
import p152 from "./wandb.js";
import p153 from "./weizerouter.js";
import p154 from "./xai.js";
import p155 from "./xiaomi-mimo.js";
import p156 from "./xiaomi-tokenplan.js";
import p157 from "./xquik.js";
import p158 from "./youcom.js";
import p159 from "./zcode.js";
import p160 from "./zcode-lite.js";
import p161 from "./zed.js";
import p162 from "./zenmux.js";
// Temporarily hidden — no tool calling support (trae SOLO agent / windsurf gRPC skip ToolCallChunk).
// Files stay on disk; re-enable by removing the name from HIDDEN in this script and
// tests/unit/provider-registry-census.test.js, then re-running the emitter.
// hidden (not imported): ./devin-cli.js
// hidden (not imported): ./trae.js
// hidden (not imported): ./windsurf.js

export default [
  p0,
  p1,
  p2,
  p3,
  p4,
  p5,
  p6,
  p7,
  p8,
  p9,
  p10,
  p11,
  p12,
  p13,
  p14,
  p15,
  p16,
  p17,
  p18,
  p19,
  p20,
  p21,
  p22,
  p23,
  p24,
  p25,
  p26,
  p27,
  p28,
  p29,
  p30,
  p31,
  p32,
  p33,
  p34,
  p35,
  p36,
  p37,
  p38,
  p39,
  p40,
  p41,
  p42,
  p43,
  p44,
  p45,
  p46,
  p47,
  p48,
  p49,
  p50,
  p51,
  p52,
  p53,
  p54,
  p55,
  p56,
  p57,
  p58,
  p59,
  p60,
  p61,
  p62,
  p63,
  p64,
  p65,
  p66,
  p67,
  p68,
  p69,
  p70,
  p71,
  p72,
  p73,
  p74,
  p75,
  p76,
  p77,
  p78,
  p79,
  p80,
  p81,
  p82,
  p83,
  p84,
  p85,
  p86,
  p87,
  p88,
  p89,
  p90,
  p91,
  p92,
  p93,
  p94,
  p95,
  p96,
  p97,
  p98,
  p99,
  p100,
  p101,
  p102,
  p103,
  p104,
  p105,
  p106,
  p107,
  p108,
  p109,
  p110,
  p111,
  p112,
  p113,
  p114,
  p115,
  p116,
  p117,
  p118,
  p119,
  p120,
  p121,
  p122,
  p123,
  p124,
  p125,
  p126,
  p127,
  p128,
  p129,
  p130,
  p131,
  p132,
  p133,
  p134,
  p135,
  p136,
  p137,
  p138,
  p139,
  p140,
  p141,
  p142,
  p143,
  p144,
  p145,
  p146,
  p147,
  p148,
  p149,
  p150,
  p151,
  p152,
  p153,
  p154,
  p155,
  p156,
  p157,
  p158,
  p159,
  p160,
  p161,
  p162,
  // hidden: devin-cli
  // hidden: trae
  // hidden: windsurf
];
