// Token Harbor — "One API for the world's leading AI models". Catalog from
// tokenharbor.ai/models (2026-08-14): `surface` ids below; free variants use
// the ":free" suffix. Standard OpenAI error envelope (invalid_api_key).
export default {
  id: "tokenharbor",
  alias: "th",
  uiAlias: "th",
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  priority: 86,
  hasFree: true,
  display: {
    name: "Token Harbor",
    icon: "anchor",
    color: "#1A1918",
    textIcon: "TH",
    website: "https://tokenharbor.ai",
    notice: { apiKeyUrl: "https://tokenharbor.ai/dashboard" },
  },
  transport: {
    baseUrl: "https://tokenharbor.ai/v1/chat/completions",
    validateUrl: "https://tokenharbor.ai/v1/models",
  },
  passthroughModels: true,
  models: [
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-fable-5", name: "Claude Fable 5" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "qwen3.8-max", name: "Qwen3.8 Max" },
    { id: "qwen3.8-2.4t-a95b", name: "Qwen3.8 2.4T A95B" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-flash:free", name: "DeepSeek V4 Flash (Free)" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash" },
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2.5:free", name: "MiMo V2.5 (Free)" },
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
  ],
  serviceKinds: ["llm"],
};
